### ISSUE TITLE
Release Beta API version

### ISSUE THREAD

**Issue by dtzar** [kubernetes-sigs/cluster-api-addon-provider-helm#160]
**User Story**

Move from alpha to beta API version, working towards GA stability with the addon provider.

/kind feature

```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/186
- [ ] https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/197
- [ ] https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/196
- [ ] https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/199
- [ ] https://github.com/kubernetes-sigs/cluster-api-addon-provider-helm/issues/65
```

**Comment by Jont828** [comment]
Did you have any criteria in mind for a beta API version? I know we talked about implementing e2e tests for a beta release tag but not the API version

**Comment by dtzar** [comment]
I like the thinking in this proposal of having just "experimental" and "stable" channels where beta would be a part of the GA channel.  
https://docs.google.com/document/d/1uZEhliv1SoQQIi2c6Wmz_n5wYMjwE9Eyr5-mW7OFDYU/edit?usp=sharing

We would merge the existing beta and GA [graduation criteria](https://gateway-api.sigs.k8s.io/concepts/versioning/#graduation-criteria) into a single unified set of requirements:

- Full conformance test coverage.
- Multiple conformant implementations.
- Widespread implementation and usage.
- At least 6 months of soak time as an alpha API.
- No significant changes for at least 1 minor release and 3 months
- Approval from subproject owners + KEP reviewers.

**Comment by Jont828** [comment]
I think that makes sense. So under that proposal, would we cut a stable release soon and keep a series of alpha/exp releases that run ahead of it?

**Comment by dtzar** [comment]
I believe the task list just created now is the criteria for a beta release.  
There is no ETA on a beta timeline.  Contributions welcome!  

We would like to have releases ~ every 2 months (even if just dep updates).
